import { createRequire } from 'node:module';
import { readFile, mkdir, writeFile, copyFile } from 'node:fs/promises';
import path from 'node:path';
const root = path.resolve(process.argv[2] || '../Devil');
const source = await readFile(path.join(root, 'deploy-commands.js'), 'utf8');
const set = name => [...source.match(new RegExp(`const ${name} = new Set\\(\\[([\\s\\S]*?)\\]\\)`))[1].matchAll(/'([^']+)'/g)].map(m => m[1]);
const globals = set('PUBLIC_GLOBAL_COMMAND_NAMES');
const main = set('PUBLIC_MAIN_GUILD_COMMAND_NAMES');
const chat = set('PUBLIC_CHAT_GUILD_COMMAND_NAMES');
const shop = await readFile(path.join(root, 'shop.js'), 'utf8');
const vip = [...shop.match(/const PREMIUM_SHOP_COMMANDS = new Set\(\[([^\]]+)/)[1].matchAll(/'([^']+)'/g)].map(m => m[1]);
const all = createRequire(import.meta.url)(path.join(root, 'deploy-commands.js')).allCommands;
const commands = all.filter(c => [...globals, ...main, ...chat].includes(c.name)).map(c => ({ ...c, mode: vip.includes(c.name) ? 'VIP' : 'Public', scope: main.includes(c.name) ? 'main' : chat.includes(c.name) ? 'chat' : 'global', category: /rank/.test(c.name) ? 'Rank' : /verify|province/.test(c.name) ? 'Roles' : /spam|safe|ban/.test(c.name) ? 'Security' : /shop|buy/.test(c.name) ? 'Shop' : /ticket|welcom/.test(c.name) ? 'Community' : 'Tools' }));
await mkdir('data', { recursive: true });
await writeFile('data/catalog.json', JSON.stringify({ syncedAt: new Date().toISOString(), commands }, null, 2));
await copyFile('lib/settings-schema.cjs', path.join(root, 'website-settings-schema.cjs'));
await mkdir('bot-integration', { recursive: true });
await copyFile('lib/settings-schema.cjs', 'bot-integration/website-settings-schema.cjs');
console.log(`Synced ${commands.length} Public/VIP commands; Private commands excluded.`);
